### ISSUE TITLE
Remove client undo functionality

### ISSUE THREAD

**Issue by svendcs** [judoassistant/judoassistant#26]
It is currently possible to undo an action that is about to be popped from the action list. This should be fixed somehow.

**Comment by svendcsvendsen** [comment]
A possible fix is to simply disallow undoing on all client programs. This would circumvent the problem completely.

The only undoing currently done on client programs is undoing scores. This can be replaced by having inverse actions of each score type.

**Comment by svendcs** [comment]
Cancelling of scores is now implemented explicitly as an action. Undoing on clients program are therefore currently not needed. Should simply remove the undoing ability.

**Comment by svendcs** [comment]
It is now simply a matter of refactoring client code to remove undoing. It will not cause any problems in its current state though.
