### ISSUE TITLE
Tatami code assert on category redraw

### ISSUE THREAD

**Issue by svendcs** [judoassistant/judoassistant#32]
The tatami updating codes appears to crash when certain categories are redrawn. Steps to reproduce:
* Create two concurrent categories on a tatami
* Start the scoreboard on that tatami
* Remove a player from one of the categories. This causes a redraw and a crash

**Comment by svendcsvendsen** [comment]
The commit 30c9a4cc847e8156c0d7c69e3580a984db2f2239 appears to have fixed the crash in TatamiMatchesModel. This, however, does not explain the web server crash caused at https://github.com/judoassistant/judoassistant/blob/30c9a4cc847e8156c0d7c69e3580a984db2f2239/src/core/stores/tatami/sequential_block_group.cpp#L122

**Comment by svendcs** [comment]
This appears to have been fixed with the bulk actions update.
